import { Inter } from "next/font/google";
import "./globals.css";
import GlobalContext from "@/context/GlobalContext";
import "tailwindcss/tailwind.css";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <main className={`${inter.variable} font-sans`}>
            <GlobalContext>{children}</GlobalContext>
          </main>
        </body>
      </SessionWrapper>
    </html>
  );
}
